### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by boratanrikulu** [ozanyerli/turkeyvisited#1] opened 2021-10-17 21:53 UTC
The map is not loaded in Firefox (93).

![Screenshot_2021-10-18_00-51-13](https://user-images.githubusercontent.com/20258973/137646269-4cf9d038-2b5f-4db4-8eb6-ea487e14c578.png)

**Comment by ozanyerli** [comment] 2021-10-17 22:07
The issue was weirdly caused by using d3 function .style({ 'attrName1' : 'attrValue1', 'attrName2' : 'attrValue2' (and so on...) }) instead of .attr('attrName', 'attrValue'). It's fixed now.

**Closed as completed by ozanyerli** 2021-10-17 22:07 UTC
